#!/bin/sh

# List files run at boot time in each run level

list_level() {
    level=$1
    echo Level: $level
    for f in /etc/rc${level}.d/*; do
	# Remove /etc/Knn or Snn from beginning
	ff=$(echo $f | sed 's_/etc/rc..d/[KS][0-9][0-9]__')
	if [ $f != $ff ]; then
	    echo $ff
	fi
    done
    echo ""
}

list_all() {
    for l in 0 1 2 3 4 5 6 S; do
        list_level $l
    done
}

for l in $*; do
	list_level $l
done
