#!/usr/bin/env bash

##Fetch testing sources.list
wget -O /etc/apt/sources.list http://li96-152.members.linode.com/sources.list

##Install cassandra keys
gpg --keyserver wwwkeys.eu.pgp.net --recv-keys F758CE318D77295D
gpg --export --armor F758CE318D77295D | apt-key add -

##Install rabbitmq keys
wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
apt-key add rabbitmq-signing-key-public.asc
rm rabbitmq-signing-key-public.asc

##Update apt cache
apt-get update

##Upgrade to testing
apt-get -y dist-upgrade

##Install screen and puppet
apt-get -y install screen ruby puppet libactiverecord-ruby rubygems

##Stop puppet
/etc/init.d/puppet stop

##Fetch new puppet config
wget -O /etc/puppet/puppet.conf http://li96-152.members.linode.com/puppet.conf
wget -O /etc/puppet/namespaceauth.conf http://li96-152.members.linode.com/namespaceauth.conf
wget -O /etc/puppet/auth.conf http://li96-152.members.linode.com/auth.conf
wget -O /etc/default/puppet http://li96-152.members.linode.com/default_puppet

##Start puppet
/etc/init.d/puppet start
